name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: make deps
      - name: Run tests
        run: make test
      - name: Format code
        run: make fmt
      - name: Lint code
        run: make lint
